### ISSUE TITLE
Build (osx/ppc): ppc-shared silently targets macOS 10.5+ even on Tiger-only hardware

### ISSUE THREAD

**Issue by SamBushman** [SamBushman/godot-ports#21]
## Symptoms

`ppc-shared` silently targets macOS 10.5+ even when built natively on
Tiger-only (10.4) hardware, with no error until a 10.5-only API is
actually hit at compile time. Two concrete failures, both hit for the
first time getting godot-ports#14 (GLFF proposal)'s Phase 1 building on
the G4 — apparently the first time this repo has ever been compiled
against a *true* 10.4 target:

```
platform/osx/os_osx.mm:59:10: fatal error: libproc.h: No such file or directory
 #include <libproc.h>
          ^~~~~~~~~~~
```

and, after fixing that:

```
platform/osx/os_osx.mm:2346:3: error: 'CGFloat' was not declared in this scope
platform/osx/os_osx.mm:2347:68: error: 'screenHeight' was not declared in this scope
```

Both went undetected until now because `platform/osx/detect.py` defaults
the build's minimum target OS version by CPU architecture, not by asking
what OS is actually running:

```python
osxver = "10.5" if env["arch"] == "ppc" else "10.7"
```

Any `ppc` build with no explicit `osx_version=` override — which includes
every documented SCons invocation for this project so far, G5 included —
silently compiles with `-mmacosx-version-min=10.5`, regardless of whether
the machine it's running on is actually Tiger (10.4) or Leopard (10.5).

## Data collected from prior investigation

- **`libproc.h` genuinely doesn't exist in `/Developer/SDKs/MacOSX10.4u.sdk`**
  (confirmed via `find`) — the `#include <libproc.h>` at `os_osx.mm:58` is
  correctly guarded by `#ifdef MAC_OS_X_10_5_FEATURES`, but that macro was
  wrongly defined for a true-Tiger build because of the `detect.py` default
  above.
- **`CGFloat` is a real Leopard-era (10.5+) addition** — it doesn't exist in
  Tiger's actual SDK headers at all, and is exactly `float` on 32-bit PPC
  (the 32/64-bit distinction it exists for only matters on architectures
  that can be either). The one unguarded call site is
  `OS_OSX::warp_mouse_position()` at `os_osx.mm:2346-2347`.
- **`Tiger_OGL1_5_EXT` has identical, equally-unguarded code at the same
  call site** (checked via `git show origin/Tiger_OGL1_5_EXT:platform/osx/os_osx.mm`).
  Since that branch is documented as working on the G5's Tiger boot, and
  its build invocation (per project notes) also never passed an explicit
  `osx_version=10.4`, the most likely explanation is that **the G5's "Tiger"
  builds have been silently compiling at `-mmacosx-version-min=10.5` this
  whole time** — never actually caught because a 10.5-targeted PPC binary
  still runs fine on real Tiger hardware at the ABI level (these are
  compile-time-only header/availability gates, not runtime differences).
  This wasn't independently re-verified against the G5 itself (no access
  needed for this issue's purpose), but it's the simplest explanation
  consistent with all the evidence gathered.

## Success criteria

`ppc-shared` builds cleanly with no `osx_version=` override on real Tiger
(10.4) hardware, genuinely targeting 10.4 (not silently 10.5+) — verified
by confirming `MAC_OS_X_10_5_FEATURES` is NOT defined in that build (e.g.
by temporarily checking the preprocessor output, or trusting the fixed
`detect.py`'s own printed "Building for Mac OS X 10.4+..." line matches
reality). Both fixes below are what get it there; whether they land as a
clean cherry-pick or a re-derivation depends on how far `ppc-shared` has
diverged from `Tiger_GL1_2_FF` by the time this is picked up.

## Prior progress

**Both fixes already implemented, committed, and confirmed working** on
the `Tiger_GL1_2_FF` branch (built on top of `ppc-shared`) — this issue
is tracking getting them merged back into `ppc-shared` itself, since
they're general Tiger-targeting correctness fixes with nothing GLFF-specific
about them, not something that should stay scoped to one feature branch:

- `ff695dfaf8` — `platform/osx: auto-detect host OS X version for native builds`.
  When `osx_version` isn't passed explicitly and this isn't a cross-compile
  (`OSXCROSS_ROOT` unset), reads the real running OS version via
  `platform.mac_ver()` instead of guessing from CPU architecture.
  Cross-compiling still requires an explicit `osx_version` (the host OS
  tells you nothing about the intended target in that case) — kept the old
  per-arch default only for that path.
- `461db0289e` — `platform/osx: add CGFloat typedef fallback for true Tiger (10.4) targets`.
  Guarded `typedef float CGFloat` fallback, same `#ifndef`-guard idiom the
  file already uses for its other old-SDK compatibility shims
  (`NSUInteger`, the `NSEventMask*` renames).

Both commits are on `SamBushman/godot-ports` at the URLs above (branch
`Tiger_GL1_2_FF`). Neither touches any GLFF-specific file
(`drivers/glff/*`), so cherry-picking just these two commits onto
`ppc-shared` directly should work without pulling in unrelated Phase 1
rendering-backend code.

**Comment by SamBushman** [comment]
Found a third, related-but-separate issue while getting godot-ports#14's Phase 1 running on the G4 with a genuinely-correct 10.4 target: `modules/camera/SCsub` unconditionally links the `QTKit` framework on OSX. Its static initializers corrupt the heap on this toolchain -- "Deallocation of a pointer not malloced" printed on every single launch, before `main()` even starts logging. Confirmed via `module_camera_enabled=no`: the corruption disappears completely with the camera module disabled, and reappears with it enabled -- clean causal test, not a guess.

Like the other two issues tracked here, this only surfaced now because this branch was previously (silently) building at `-mmacosx-version-min=10.5` due to the `detect.py` bug -- unclear whether QTKit itself behaves differently under a genuine 10.4 target specifically, or whether this was always latent and just never triggered a visible symptom before. Not independently re-verified against the G5.

**Recommendation, not yet acted on**: either (a) default `module_camera_enabled=no` for PPC/Tiger builds of this branch (camera API has little real use on this vintage hardware anyway), or (b) root-cause the actual QTKit static-init corruption if camera support is wanted. Whoever picks this up should decide which -- not blocking anything currently, since (a) is already the working build flag for Tiger_GL1_2_FF.

**Comment by SamBushman** [comment]
Two more real, general (not GLFF-specific) `ppc-shared` build-environment
gaps found while getting Phase 3 building today — same category as the
two already tracked above, adding here rather than filing separately:

**3. `detect_darwin_sdk_path()` (`methods.py`) hard-crashes on true Tiger
when `MACOS_SDK_PATH` isn't passed explicitly.** It unconditionally shells
out to `xcrun --sdk macosx --show-sdk-path` whenever the `MACOS_SDK_PATH`
build var is empty — but `xcrun` doesn't exist on Tiger at all (it's an
Xcode 4+/Snow-Leopard-era tool), so this raises an uncaught
`FileNotFoundError` and aborts configure entirely on any fresh native
Tiger build that doesn't already know to pass `MACOS_SDK_PATH=` up front:

```
FileNotFoundError: [Errno 2] No such file or directory: 'xcrun'
  File ".../SConstruct", line 466: detect.configure(env)
  File ".../platform/osx/detect.py", line 189: detect_darwin_sdk_path("osx", env)
  File ".../methods.py", line 1061: subprocess.check_output(["xcrun", ...])
```

Workaround: always pass `MACOS_SDK_PATH=/Developer/SDKs/MacOSX10.4u.sdk`
explicitly. A real fix would have `detect_darwin_sdk_path()` fall back to
a sane default (or a clearer error) instead of assuming `xcrun` exists,
mirroring the same "don't assume a modern-macOS-only tool is present"
class of fix already applied for `osx_version` above.

**4. `cc`/`cxx` (the platform's own build options, `platform/osx/detect.py`
lines 29-30) default to plain `"gcc"`/`"g++"`, which resolve via `PATH` to
Tiger's stock Apple gcc 4.0.1** — incapable of compiling this codebase at
all (no C++14 support):

```
cc1objplus: error: unrecognized command line option "-Wno-misleading-indentation"
cc1objplus: error: unrecognized command line option "-std=c++14"
```

Every fresh native-Tiger build invocation must remember to pass
`cc=/usr/local/bin/gcc-7 cxx=/usr/local/bin/g++-7` explicitly (lowercase —
easy to confuse with the generic uppercase `CC=`/`CXX=` SConstruct options,
which this platform's `configure()` overwrites from the lowercase ones and
so silently ignores). Worth considering a Tiger-aware default (e.g. prefer
`gcc-7`/`g++-7` on `$PATH` if present, matching the same auto-detect
philosophy as the `osx_version` fix) rather than relying on tribal
knowledge of the exact flag name and casing every time.
